### ISSUE TITLE
Allow saving / exporting rescaled copy numbers for a given purity and ploidy

### ISSUE THREAD

**Issue by lbeltrame** [crukci-bioinformatics/rascal#1]
The two tools rascal is compared to in the Biorxiv preprint allow either automatically (ichorCNA) or with some manual intervention (`postanalsysisloop` function in ACE) to output the segments with the calculated copy number (ACE; decimal, i.e. not a truly absolute copy number) or the copy number call (ichorCNA).

A use case for such a feature is to enable post-processing in downstream applications knowing that the values (absolute CN/relative CN/log2ratio) have been properly adjusted for purity and ploidy. For example GISTIC to call recurrent alterations, or to perform some extra calculations like copy number burden, or the fraction of subclonal segments as discussed in preprint itself. 

While it's relatively easy to rescale the log ratios for a chosen estimate of purity and ploidy, having a function that would generate segments in a DNAcopy-compatible format with the addition of relative and absolute copy number calls per segment would be very useful.

**Comment by TBradley27** [comment]
Hi Luca,

Thank you for taking an interest in the rascal tool, and raising this issue here.

I believe `rascal::relative_to_absolute_copy_number` performs the requested functionality. Documentation for this function can be found by entering `?rascal::relative_to_absolute_copy_number` in the R console. The first argument to this function is a vector of relative copy number values (_e.g._ a vector of relative copy number segment values). The second argument is the ploidy. The third argument is the purity.

The output is a numeric vector of absolute copy number values.

Does this answer your question, and produce the desired results?

Matt (@eldrid01), the package developer or Carolin (@cmsauer) will be able to correct me if I have made a mistake here.

**Comment by eldrid01** [comment]
Hi Luca,

This is a very good suggestion and I'll add it to my todo list. You can use the R functions as Thomas rightly points out and that's what we've been doing in a scripted batch process. We use the Shiny app to help decide between competing solutions where supporting evidence such as a clonal TP53 mutation doesn't differentiate these sufficiently well.

The R functions are relatively well documented but I still have to create a vignette (also on the todo list) which will show how these are expected to be run in a small workflow.

I'll see if I can add the save function for segmented copy numbers, both relative and scaled/absolute, in the next few days.

Matt

**Comment by cmsauer** [comment]
Hi Luca, 

As both Thomas, and Matt have already pointed out, we have been using the rascal::relative_to_absolute_copy_number function for this, and then exported the generated data for downstream analyses. 
I think it's a great suggestion though to have a function to automatically generate and save the segmented copy number data, thank you!

Carolin

**Comment by eldrid01** [comment]
Hi Luca, I've added a Save button to the Shiny app for exporting the scaled segmented copy number for the current sample and the selected ploidy and cellularity. The output is a CSV file with columns for both relative and absolute copy numbers, e.g.

chromosome,start,end,bins,log2_ratio,relative_copy_number,absolute_copy_number
1,840001,149220000,3828,0.042,1.03,3.026
1,149850001,152010000,71,0.503,1.417,4.913
1,152010001,153480000,46,0.188,1.139,3.558
1,153480001,155430000,65,0.395,1.315,4.416
1,155430001,156300000,26,0.879,1.838,6.972

Does this seem ok to you?

**Comment by lbeltrame** [comment]
It would work, indeed. Without having looked at the code yet: is there a function to do this GUI-less?

**Comment by slw287r** [comment]
> It would work, indeed. Without having looked at the code yet: is there a function to do this GUI-less?

https://github.com/crukci-bioinformatics/rascal/blob/08bdf79bfcf9e98f7f83967a71c16b4a6f272684/R/utils.R#L3-L5
https://github.com/crukci-bioinformatics/rascal/blob/08bdf79bfcf9e98f7f83967a71c16b4a6f272684/R/utils.R#L21-L23

**Comment by eldrid01** [comment]
Hi Luca,

I've just added a vignette and released a new version of the package that contains both this and the new Save function in the Shiny app. The vignette provides a walk-through the functions available in the R package. These functions are used by the Shiny app but can be run separately in an R session and the vignette shows how to do this. Each of the functions was already documented but the vignette was missing before.

There is also a helper script for batch fitting of copy number data from multiple samples that might be of interest. Details on how to run this are in the vignette and on one of the wiki pages attached to this GitHub repository. The fit_absolute_copy_numbers.R script can be found in the inst/scripts directory.

For convenience, and because the package isn't yet released on Bioconductor or CRAN, I've attached a rendered html version of the vignette to this issue ([rascal_0.7.0_vignette.html.gz](https://github.com/crukci-bioinformatics/rascal/files/6933012/rascal_0.7.0_vignette.html.gz) - couldn't upload the html file without compressing it first).

Hope that helps,
Matt

**Comment by lbeltrame** [comment]
Thanks, I'll give it a go tomorrow.

**Comment by TBradley27** [comment]
Hi Luca (@lbeltrame),

Just checking, but did Matt's changes/comments solve this issue for you?

Best wishes,
Thomas

**Comment by lbeltrame** [comment]
Whoops, sorry, this notification slipped under the radar. I actually did test and it mostly worked for me. If I find more specific problems I'll file relevant issue.
